field: b698e2c0-731b-49d6-bd16-5af803cfd848
fieldLayouts:
  c6049641-f52a-47f7-9e5e-c7c18405c86b:
    tabs:
      -
        elements:
          -
            fieldUid: 5a78ca15-7d2d-4f57-9f70-8186660af1f3
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: e61c6a1e-9008-49df-a4c4-73eea0635e4d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  5a78ca15-7d2d-4f57-9f70-8186660af1f3:
    contentColumnType: text
    fieldGroup: null
    handle: linkName
    instructions: ''
    name: name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e61c6a1e-9008-49df-a4c4-73eea0635e4d:
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: ''
    name: url
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: navLinkItem
name: 'Link item'
sortOrder: 1
