field: 98a3a646-c98c-4cd5-8a21-370da111f169
fieldLayouts:
  c49ff90f-6350-4d88-93ab-3e84520630d9:
    tabs:
      -
        elements:
          -
            fieldUid: a08a5157-ff0b-4aef-8d78-8588b67dab49
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 14398e4d-2b0f-4c44-95e4-d8afa08aca30
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 558f1038-83ae-4926-8af4-7c9d7891eb9d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2998aa07-b629-4f56-9966-4650f737f29a
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 3e7b8d67-5288-4062-868b-1d3453648f91
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  14398e4d-2b0f-4c44-95e4-d8afa08aca30:
    contentColumnType: text
    fieldGroup: null
    handle: tabTitle
    instructions: 'The big title'
    name: 'Tab Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2998aa07-b629-4f56-9966-4650f737f29a:
    contentColumnType: text
    fieldGroup: null
    handle: tabLinkName
    instructions: 'Link under description'
    name: 'Tab Link Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3e7b8d67-5288-4062-868b-1d3453648f91:
    contentColumnType: string(255)
    fieldGroup: null
    handle: tabLinkUrl
    instructions: 'Url for tab link'
    name: 'Tab Link Url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  558f1038-83ae-4926-8af4-7c9d7891eb9d:
    contentColumnType: text
    fieldGroup: null
    handle: tabDescription
    instructions: 'Displayed under big title'
    name: 'Tab Description'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a08a5157-ff0b-4aef-8d78-8588b67dab49:
    contentColumnType: text
    fieldGroup: null
    handle: tabName
    instructions: 'Displayed at tab button'
    name: 'Tab Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: tab
name: tab
sortOrder: 1
