contentColumnType: string
fieldGroup: 0ac481cb-23cc-4aff-a8d6-6ecf2a734663
handle: containerEpsilonFields
instructions: 'Fifth block at the home page'
name: 'Container Epsilon Fields'
searchable: false
settings:
  contentTable: '{{%matrixcontent_containerepsilonfields}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
