contentColumnType: string
fieldGroup: 09ced2aa-68de-47be-b6b3-26839ab289a9
handle: navigationLinks
instructions: ''
name: 'Navigation links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigationlinks}}'
  maxBlocks: '6'
  minBlocks: '6'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
