fieldLayouts:
  83461bd1-d979-4fb1-925c-be6256ba4d21:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 8dfa05ac-5704-4025-b5b5-d08eb32af006
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Container Alpha'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 98a3a646-c98c-4cd5-8a21-370da111f169
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Container Beta'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: ef49d1ce-6764-4df9-9de8-6d48b03bc3e6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Container Gamma'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 40c74096-a435-4760-9211-4bd31266156d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Container Delta'
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 613dab12-cd8f-424c-8eb8-49f1f03c0a07
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Container Epsilon'
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 6a0f9954-7bd8-42a7-8efa-ccd6a87e6409
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Container Map'
        sortOrder: 6
handle: homePage
hasTitleField: false
name: 'Home page'
section: 9b806f50-8544-4873-a181-e9ba626ac9d2
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
